[themes.default]
# The symbol marking the default device on the Input/Output Devices tabs
default_device = { }
# The symbol marking the default endpoint on the Playback/Recording tabs
default_stream = { }
# The selection indicator in a tab
selector = { fg = "#59E3E3" }
# The name of a tab in the tab menu
tab = { }
# The name of the selected tab in the tab menu
tab_selected = { fg = "#59E3E3" }
# The symbols surrounding the selected tab in the tab menu
tab_marker = { fg = "#59E3E3" }
# The symbol at the top/bottom of a tab indicating that there are more items
list_more = { fg = "#232530" }
# The name of a PipeWire node
node_title = { fg = "#EE64AE" }
# The name of the selected target for a node
node_target = { }
# The volume percentage label
volume = { }
# Volume bar
volume_empty = { fg = "#232530" }
volume_filled = { fg = "#26BBD9" }
# Peak meter. Inactive = unlit, active = lit, overload = greater than 0.0 dB
meter_inactive = { fg = "DarkGray" }
meter_active = { fg = "#29D398" }
meter_overload = { fg = "Red" }
# The "live" indicator in the center of the meter
meter_center_inactive = { fg = "#232530" }
meter_center_active = { fg = "#29D398" }
# The name of a device in the Configuration tab
config_device = { }
# The name of the selected profile in the Configuration tab
config_profile = { }
# Dropdown marker next to the profiles in the Configuration tab
dropdown_icon = { }
# Border around dropdowns
dropdown_border = { }
# The name of an item in a dropdown
dropdown_item = { }
# The name of the currently-selected item in a dropdown
dropdown_selected = { fg = "#59E3E3", add_modifier = "REVERSED" }
# The symbol at the top/bottom of a dropdown indicating that there are more
# items
dropdown_more = { fg = "#232530" }
# Border around help menu
help_border = { }
# The name of an item in a the help menu
help_item = { }
# The symbol at the top/bottom of the help menu indicating that there are more
# items
help_more = { fg = "#232530" }
