[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 7

# The default session, also known as the greeter.
[default_session]

# `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# with whatever you want started, such as `sway`.
# command = "agreety --cmd /bin/sh"
# border=magenta;text=cyan;prompt=cyan;time=red;action=blue;button=blue;container=black;input=red  
command = "/usr/bin/tuigreet --time --asterisks --remember --theme 'text=white;time=bright-white;greet=magenta;prompt=white;input=cyan;border=white;container=bright-black;action=black;button=black' --cmd /usr/bin/startx"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "greeter"
